### ISSUE TITLE
hello, how to install docker-grocy with traefik?

### ISSUE THREAD

**Issue by ivanhertanto** [linuxserver/docker-grocy#22]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
I want install docker-grocy with docker-traefik 

## Current Behavior
but I get error 502

## Steps to Reproduce
1. git clone
2. docker-compose up -d

## Environment
**OS:** Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64 GNU/Linux
**CPU architecture:**x68_64
**How docker service was installed:**      

## Command used to create docker container (run/create/compose/screenshot)

docker-compose.yml :
```
version: '2.1'

networks:
  web:
    external: true

services:
  grocy:
    image: linuxserver/grocy
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
    volumes:
      - ./config:/config
    restart: unless-stopped
    labels:
      - traefik.backend=grocy
      - traefik.frontend.rule=Host:grocy.hertanto.com
      - traefik.docker.network=web
      - traefik.port=9283
    networks:
      - web
    ports:
      - 9283:80
```

## Docker logs
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing...
[cont-init.d] 50-config: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

```
