### ISSUE TITLE
iCal Calendar not working - chore -> Dynamic regular

### ISSUE THREAD

**Issue by hanspeter1** [linuxserver/docker-grocy#51]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
iCal Link is working -> https://<domain>/api/calendar/ical?secret=<secret>

## Current Behavior
Error: "Eluceo\\iCal\\Domain\\ValueObject\\PointInTime::__construct(): Argument #1 ($dateTime) must be of type ?DateTimeInterface, bool given, called in /app/grocy/controllers/CalendarApiController.php on line 33"

## Steps to Reproduce

1. iCal Link is working (No error)
2. Set new chore -> Period type = Dynamic regular or Weekly (if a Day of a Week is not selected) -> Save
3. iCal Link is not working (see Current Behavior)
4. Delete chore -> iCal Link is working

## Environment
**OS:** Ubuntu 20.04
**CPU architecture:** x86_64
**How docker service was installed:**
Portainer 2.6.3 with https://github.com/linuxserver/docker-grocy#docker-compose-recommended-click-here-for-more-info

## Command used to create docker container (run/create/compose/screenshot)
```
version: "2.1"
services:
  grocy:
    image: ghcr.io/linuxserver/grocy:amd64-latest
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /mnt/vmDaten/Grocy:/config
    ports:
      - 9283:80
    restart: unless-stopped
```
